// modules/pcc_config.js

export const PCC_FIELDS = {
    "P12_PASSPORT_NO": { "name": "P12_PASSPORT_NO", "label": "Passport No" },
    "P12_NATIONALITY": { "name": "P12_NATIONALITY", "label": "Issuing Country" },
    "P12_ISSUE_DATE": { "name": "P12_ISSUE_DATE", "label": "Issue Date (DD-MON-YYYY)" },
    "P12_ISSUE_PLACE": { "name": "P12_ISSUE_PLACE", "label": "Issue Place" },
    "P12_EXPIRE_DATE": { "name": "P12_EXPIRE_DATE", "label": "Expiry Date (DD-MON-YYYY)" },
    "P12_MOBILE_NO": { "name": "P12_MOBILE_NO", "label": "Mobile No (Applicant)" },
    "P12_EMAIL": { "name": "P12_EMAIL", "label": "Email ID (Applicant)" },
    "P12_NID": { "name": "P12_NID", "label": "NID (Numbers only)" },
    "P12_GENDER": { "name": "P12_GENDER", "label": "Salutation (Mr./Ms./None)" },
    "P12_PERSON_NAME": { "name": "P12_PERSON_NAME", "label": "Full Name" },
    "P12_RELATION": { "name": "P12_RELATION", "label": "Relation (Father/Spouse)" },
    "P12_FATHER_NAME": { "name": "P12_FATHER_NAME", "label": "Father's / Husband Name" },
    "P12_MOTHER_NAME": { "name": "P12_MOTHER_NAME", "label": "Mother's Name" },
    "P12_DOB": { "name": "P12_DOB", "label": "Date of Birth (DD-MON-YYYY)" },

    "P60_EMER_PUBLIC_DIVISION": { "name": "P60_EMER_PUBLIC_DIVISION", "label": "Emergency Division" },
    "P60_EMER_DISTRICT": { "name": "P60_EMER_DISTRICT", "label": "Emergency District" },
    "P60_EMER_THANA": { "name": "P60_EMER_THANA", "label": "Emergency Thana" },
    "P60_EMER_POST_CODE": { "name": "P60_EMER_POST_CODE", "label": "Emergency Post Code" },
    "P60_EMER_POST_OFFICE": { "name": "P60_EMER_POST_OFFICE", "label": "Emergency Post Office" },
    "P60_EMER_VILL_AREA": { "name": "P60_EMER_VILL_AREA", "label": "Emergency Village/Area/Sector" },
    "P60_EMER_HOUSE_ROAD": { "name": "P60_EMER_HOUSE_ROAD", "label": "Emergency Road" },
    "P60_EMER_HOUSE": { "name": "P60_EMER_HOUSE", "label": "Emergency House" },

    "P60_SET_PERM_ADDRESS": { "name": "P60_SET_PERM_ADDRESS", "label": "Permanent Address Match (emer/man)" },
    "P60_PERM_PUBLIC_DIVISION": { "name": "P60_PERM_PUBLIC_DIVISION", "label": "Permanent Division" },
    "P60_PERM_DISTRICT": { "name": "P60_PERM_DISTRICT", "label": "Permanent District" },
    "P60_PERM_THANA": { "name": "P60_PERM_THANA", "label": "Permanent Thana" },
    "P60_PERM_POST_CODE": { "name": "P60_PERM_POST_CODE", "label": "Permanent Post Code" },
    "P60_PERM_POST_OFFICE": { "name": "P60_PERM_POST_OFFICE", "label": "Permanent Post Office" },
    "P60_PERM_VILL_AREA": { "name": "P60_PERM_VILL_AREA", "label": "Permanent Village/Area/Sector" },
    "P60_PERM_HOUSE_ROAD": { "name": "P60_PERM_HOUSE_ROAD", "label": "Permanent Road" },
    "P60_PERM_HOUSE": { "name": "P60_PERM_HOUSE", "label": "Permanent House" },

    "P60_SET_PRES_ADDRESS": { "name": "P60_SET_PRES_ADDRESS", "label": "Present Address Match (emer/perm/man)" },
    "P60_PRES_PUBLIC_DIVISION": { "name": "P60_PRES_PUBLIC_DIVISION", "label": "Present Division" },
    "P60_PRES_DISTRICT": { "name": "P60_PRES_DISTRICT", "label": "Present District" },
    "P60_PRES_THANA": { "name": "P60_PRES_THANA", "label": "Present Thana" },
    "P60_PRES_POST_CODE": { "name": "P60_PRES_POST_CODE", "label": "Present Post Code" },
    "P60_PRES_POST_OFFICE": { "name": "P60_PRES_POST_OFFICE", "label": "Present Post Office" },
    "P60_PRES_VILL_AREA": { "name": "P60_PRES_VILL_AREA", "label": "Present Village/Area/Sector" },
    "P60_PRES_HOUSE_ROAD": { "name": "P60_PRES_HOUSE_ROAD", "label": "Present Road" },
    "P60_PRES_HOUSE": { "name": "P60_PRES_HOUSE", "label": "Present House" },

    "P60_DELIVERY_TYPE": { "name": "P60_DELIVERY_TYPE", "label": "Delivery Type" },
    "P60_DELIVERY_FROM": { "name": "P60_DELIVERY_FROM", "label": "Delivery From" }
};

export const PCC_DUMMY_PROFILE = {
    id: 'p_pcc_dummy',
    name: 'PCC Default Profile',
    site: 'pcc',
    data: {
        "P12_PASSPORT_NO": "",
        "P12_NATIONALITY": "",
        "P12_ISSUE_DATE": "",
        "P12_ISSUE_PLACE": "",
        "P12_EXPIRE_DATE": "",
        "P12_MOBILE_NO": "",
        "P12_EMAIL": "",
        "P12_NID": "",
        "P12_GENDER": "",
        "P12_PERSON_NAME": "",
        "P12_RELATION": "",
        "P12_FATHER_NAME": "",
        "P12_MOTHER_NAME": "",
        "P12_DOB": "",

        "P60_EMER_PUBLIC_DIVISION": "",
        "P60_EMER_DISTRICT": "",
        "P60_EMER_THANA": "",
        "P60_EMER_POST_CODE": "",
        "P60_EMER_POST_OFFICE": "",
        "P60_EMER_VILL_AREA": "",
        "P60_EMER_HOUSE_ROAD": "",
        "P60_EMER_HOUSE": "",

        "P60_SET_PERM_ADDRESS": "",
        "P60_PERM_PUBLIC_DIVISION": "",
        "P60_PERM_DISTRICT": "",
        "P60_PERM_THANA": "",
        "P60_PERM_POST_CODE": "",
        "P60_PERM_POST_OFFICE": "",
        "P60_PERM_VILL_AREA": "",
        "P60_PERM_HOUSE_ROAD": "",
        "P60_PERM_HOUSE": "",

        "P60_SET_PRES_ADDRESS": "",
        "P60_PRES_PUBLIC_DIVISION": "",
        "P60_PRES_DISTRICT": "",
        "P60_PRES_THANA": "",
        "P60_PRES_POST_CODE": "",
        "P60_PRES_POST_OFFICE": "",
        "P60_PRES_VILL_AREA": "",
        "P60_PRES_HOUSE_ROAD": "",
        "P60_PRES_HOUSE": "",

        "P60_DELIVERY_TYPE": "",
        "P60_DELIVERY_FROM": ""
    }
};